export type Product = {
  id: string
  name: string
  category: string
  price: number
  /** Raw supplier cost before margin (used by the admin calculator). */
  baseCost: number
  image: string
  inStock: boolean
}

export function formatINR(value: number): string {
  return `₹${value.toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`
}

// Margin added to the base (supplier) price, tiered by base price.
export function applyMargin(basePrice: number): number {
  let margin = 0
  if (basePrice >= 3000) margin = 150
  else if (basePrice >= 999) margin = 70
  else if (basePrice >= 400) margin = 50
  else if (basePrice >= 230) margin = 35
  else if (basePrice >= 150) margin = 20
  else if (basePrice >= 70) margin = 15
  else if (basePrice >= 30) margin = 7
  else if (basePrice >= 10) margin = 3
  else margin = 1
  return basePrice + margin
}

const raw: Array<Omit<Product, "id" | "inStock"> & { inStock?: boolean }> = [
  // Accesories & Cables
  { name: "60W soldering iron with temperature control", category: "Accesories & Cables", price: 280, image: "https://robboquad.com/wp-content/uploads/2026/06/Soldering-Iron-60W.png" },
  { name: "6x6x5 Tactile push button switch (non latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/6x6x5-Tactile-push-button-switch-non-latching.png" },
  { name: "6x6x6 Tactile push button switch (non latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/6x6x6-Tactile-push-button-switch-non-latching.png" },
  { name: "6x6x7 Tactile push button switch (non latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/6x6x7-Tactile-push-button-switch-non-latching.png" },
  { name: "6x6x8 Tactile push button switch (non latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/6x6x8-Tactile-push-button-switch-non-latching.png" },
  { name: "6x6x9 Tactile push button switch (non latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/6x6x9-Tactile-push-button-switch-non-latching.png" },
  { name: "7x7x14 Tactile push switch (latching)", category: "Accesories & Cables", price: 5, image: "https://robboquad.com/wp-content/uploads/2026/06/7x7x14-Tactile-push-switch-latching-2.png" },
  { name: "800 Point Solderless Breadboard – Full Size Prototyping Board", category: "Accesories & Cables", price: 74, image: "https://robboquad.com/wp-content/uploads/2026/06/Breadboard-800-Points-Solderless.png" },
  { name: "9v HW Battery Cap", category: "Accesories & Cables", price: 7, image: "https://robboquad.com/wp-content/uploads/2026/06/9V-battery-cap-.png" },
  { name: "Arduino 9V Battery Connector with DC Jack", category: "Accesories & Cables", price: 19, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-9v-Connector-power.png" },
  { name: "Arduino Nano USB Cable High Quality USB to Mini-B Cable", category: "Accesories & Cables", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Nano-USB-Cable.png" },
  { name: "Arduino Uno USB Cable – High-Speed USB Type-A to B Cable", category: "Accesories & Cables", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Uno-USB-Cable.png" },
  { name: "Breadboard 400 Points – Solderless Prototyping Board for Arduino & Electronics Projects", category: "Accesories & Cables", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/Breadboard-400-Points-Solderless.png" },
  { name: "Buzzer Large 9v -12v", category: "Accesories & Cables", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/robbuquad.jpg" },
  { name: "DC jack Male with wire", category: "Accesories & Cables", price: 7, image: "https://robboquad.com/wp-content/uploads/2026/06/DC-jack-Male-with-wire.png" },
  { name: "Digital Multimeter – AC/DC Voltage, Current, Resistance Tester for Electronics Projects", category: "Accesories & Cables", price: 209, image: "https://robboquad.com/wp-content/uploads/2026/06/Multimeter.png" },
  { name: "Female Dc jack wire", category: "Accesories & Cables", price: 25, image: "https://robboquad.com/wp-content/uploads/2026/06/Female-Dc-jack-wire.png" },
  { name: "Female Headers – Pack of 5 Pieces", category: "Accesories & Cables", price: 65, image: "https://robboquad.com/wp-content/uploads/2026/06/131.png" },
  { name: "Female Power Connector for Arduino – 9v/12V", category: "Accesories & Cables", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/130.png" },
  { name: "Female to Female Connecting Wires – 20CM", category: "Accesories & Cables", price: 75, image: "https://robboquad.com/wp-content/uploads/2026/06/Female-to-Female-Connecting-Wires.png" },
  { name: "Female to Female Jumper Wires – 40 PCS", category: "Accesories & Cables", price: 60, image: "https://robboquad.com/wp-content/uploads/2026/06/Female-to-Female-Jumper-Wires-40-PCS.png" },
  { name: "Glue Gun 60Watts", category: "Accesories & Cables", price: 250, image: "https://robboquad.com/wp-content/uploads/2026/06/Glue-gun-60W.png" },
  { name: "Glue Stick Large 5 Nos", category: "Accesories & Cables", price: 75, image: "https://robboquad.com/wp-content/uploads/2026/06/glue-stick.png" },
  { name: "Male Headers 2.54mm", category: "Accesories & Cables", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/Male-Header-2.54mm.png" },
  { name: "Male Power Connector for Arduino – 9v/12V", category: "Accesories & Cables", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/130.png" },
  { name: "Male to Female Connecting Wires – 20CM", category: "Accesories & Cables", price: 75, image: "https://robboquad.com/wp-content/uploads/2026/06/Male-to-Female-connecting-wires.png" },
  { name: "Male to Female Jumper Wires – 40 PCS", category: "Accesories & Cables", price: 60, image: "https://robboquad.com/wp-content/uploads/2026/06/Male-to-Female-Jumper-Wires-40-PCS.png" },
  { name: "Male to Male Connecting Wires – 20CM", category: "Accesories & Cables", price: 75, image: "https://robboquad.com/wp-content/uploads/2026/06/Male-to-Male-Connecting-wires.png" },
  { name: "Male to Male Jumper Wires – 40 PCS", category: "Accesories & Cables", price: 60, image: "https://robboquad.com/wp-content/uploads/2026/06/Male-to-Male-Jumper-Wires-40-PCS.png" },
  { name: "Micro usb type B cable for esp32", category: "Accesories & Cables", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/Micro-USB-Type-B.png" },
  { name: "Mini Breadboard 70 Points – Solderless Prototyping Board for Arduino & DIY Projects", category: "Accesories & Cables", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/Breadboard-70-Points-Solderless.png" },
  { name: "Perfboard for Prototyping for DIY Electronics", category: "Accesories & Cables", price: 89, image: "https://robboquad.com/wp-content/uploads/2026/06/Perfboard.png" },
  { name: "RC522 RFID Cards 13.56MHz MIFARE Classic 1K", category: "Accesories & Cables", price: 15, image: "https://robboquad.com/wp-content/uploads/2026/07/RC522-RFID-Cards.png" },
  { name: "Servo Tester 5v Module", category: "Accesories & Cables", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/Servo-Tester-5v-Module.png" },
  { name: "Slide Switch", category: "Accesories & Cables", price: 250, image: "https://robboquad.com/wp-content/uploads/2026/06/Slide-Switch.png" },
  { name: "Soldering Iron 25 Watts", category: "Accesories & Cables", price: 250, image: "https://robboquad.com/wp-content/uploads/2026/06/soldering-iron-25W.png" },
  { name: "Soldering Stand", category: "Accesories & Cables", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/soldering-stand.png" },
  { name: "Wire 22 AWG ( 1 Mtr )", category: "Accesories & Cables", price: 30, image: "https://robboquad.com/wp-content/uploads/2026/06/wire-22-awg.png" },
  { name: "Wire Stripper", category: "Accesories & Cables", price: 95, image: "https://robboquad.com/wp-content/uploads/2026/06/Wire-stripper.png" },
  // Arduino Boards
  { name: "Arduino Mega CH340", category: "Arduino Boards", price: 1199, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Mega-CH340.png" },
  { name: "Arduino Nano R3 CH340 Soldered", category: "Arduino Boards", price: 269, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Nano-R3-CH340-Soldered.png" },
  { name: "Arduino Nano R3 CH340 Un-Soldered", category: "Arduino Boards", price: 259, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Nano-R3-CH340-Un-Soldered.png" },
  { name: "Arduino Uno R3 ATmega328p Compaitable DIP Version", category: "Arduino Boards", price: 499, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Uno-R3-DIP-Version-.png" },
  { name: "Arduino Uno SMD R3 Compaitable", category: "Arduino Boards", price: 269, image: "https://robboquad.com/wp-content/uploads/2026/06/Arduino-Uno-SMD-R3-Compaitable-.png" },
  // Combo Products
  { name: "Combo – 1 Cell 18650 Rechargeable Li-ion Battery with 1 Cell Battery Holder", category: "Combo Products", price: 129, image: "https://robboquad.com/wp-content/uploads/2026/06/90.png" },
  { name: "Combo – 100 RPM BO Motor for Robotic Car (2 Pieces)", category: "Combo Products", price: 129, image: "https://robboquad.com/wp-content/uploads/2026/06/82.png" },
  { name: "Combo – 100 RPM BO Motor for Robotic Car (4 Pieces)", category: "Combo Products", price: 249, image: "https://robboquad.com/wp-content/uploads/2026/06/83.png" },
  { name: "Combo – 100 RPM BO Motor for Robotic Car (4 Pieces)", category: "Combo Products", price: 249, image: "https://robboquad.com/wp-content/uploads/2026/06/83.png" },
  { name: "Combo – 100K Potentiometer (5 Pieces) – Variable Resistors", category: "Combo Products", price: 49, image: "https://robboquad.com/wp-content/uploads/2026/06/87.png" },
  { name: "Combo – 10K Potentiometer (5 Pieces) – Variable Resistors", category: "Combo Products", price: 49, image: "https://robboquad.com/wp-content/uploads/2026/06/86.png" },
  { name: "Combo – 2 Cell 18650 Rechargeable Li-ion Battery with 2 Cell Battery Holder", category: "Combo Products", price: 249, image: "https://robboquad.com/wp-content/uploads/2026/06/91.png" },
  { name: "Combo – 3 Cell 18650 Rechargeable Li-ion Battery with 3 Cell Battery Holder", category: "Combo Products", price: 399, image: "https://robboquad.com/wp-content/uploads/2026/06/92.png" },
  { name: "Combo – Arduino Uno R3 ATmega328p Compaitable Dip Version with Cable", category: "Combo Products", price: 549, image: "https://robboquad.com/wp-content/uploads/2026/06/77.png" },
  { name: "Combo – BO Wheel for Robotic Car (2 Pieces)", category: "Combo Products", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/78.png" },
  { name: "Combo – BO Wheel for Robotic Car (4 Pieces)", category: "Combo Products", price: 109, image: "https://robboquad.com/wp-content/uploads/2026/06/79.png" },
  { name: "Combo – BO Wheel with 100 RPM BO Motors (2 Pieces)", category: "Combo Products", price: 189, image: "https://robboquad.com/wp-content/uploads/2026/06/81.png" },
  { name: "Combo – Jumper Wires All Types (Male to Male, Male to Female, Female to Female) each type 40 Pieces", category: "Combo Products", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/96.png" },
  { name: "Combo – Jumper Wires each type 20 Pieces with 800 points Breadboard", category: "Combo Products", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/100.png" },
  { name: "Combo – L293D Motor Driver Shield for Arduino Uno (2 Pieces)", category: "Combo Products", price: 269, image: "https://robboquad.com/wp-content/uploads/2026/06/89.png" },
  { name: "Combo – L29N Motor Driver Shield for Arduino/Raspberry PI (2 Pieces)", category: "Combo Products", price: 259, image: "https://robboquad.com/wp-content/uploads/2026/06/88.png" },
  { name: "Combo – Relay 1 Channel 5V for Arduino/Raspberry Pi (2 Pieces)", category: "Combo Products", price: 109, image: "https://robboquad.com/wp-content/uploads/2026/06/93.png" },
  { name: "Combo – Relay 2 Channel 5V for Arduino/Raspberry PI (2 Pieces)", category: "Combo Products", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/95.png" },
  { name: "Combo – Relay 4 Channel 5V for Arduino/Raspberry Pi (2 Pieces)", category: "Combo Products", price: 329, image: "https://robboquad.com/wp-content/uploads/2026/06/94.png" },
  { name: "Combo – SG 90 Tower Pro Servo Motor (2 Pieces)", category: "Combo Products", price: 249, image: "https://robboquad.com/wp-content/uploads/2026/06/84.png" },
  { name: "Combo – SG 90 Tower Pro Servo Motor (4 Pieces)", category: "Combo Products", price: 499, image: "https://robboquad.com/wp-content/uploads/2026/06/85.png" },
  // Display Board & LED
  { name: "0.96 Inch OLED Display Module (SPI/I2C, 4-Pin, Blue) for Arduino, ESP32 & Raspberry Pi", category: "Display Board & LED", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/Oled-0.96-inch.png" },
  { name: "2.4 inch SPI interface TFT LCD touch display", category: "Display Board & LED", price: 890, image: "https://robboquad.com/wp-content/uploads/2026/06/2.4-inch-SPI-interface-TFT-LCD-touch-display.png" },
  { name: "5mm Blue Diffused LED", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/06/136.png" },
  { name: "5mm Blue Diffused LED", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/06/136.png" },
  { name: "5mm LDR Sensor | Light Dependent Resistor", category: "Display Board & LED", price: 10, image: "https://robboquad.com/wp-content/uploads/2026/06/5mm-LDR.png" },
  { name: "5mm Red LED Diode", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/06/139.png" },
  { name: "5mm Yellow Diffused LED", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/06/137.png" },
  { name: "7 segment display", category: "Display Board & LED", price: 15, image: "https://robboquad.com/wp-content/uploads/2026/06/TSOP-IR-Receiver-VS1838B-2.png" },
  { name: "Green LED – 5mm", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/06/140.png" },
  { name: "I2C Module for 16&#215;2 LCD Display", category: "Display Board & LED", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/I2C-Module-for-LCD-16x2-1.png" },
  { name: "laser Red 650nm", category: "Display Board & LED", price: 25, image: "https://robboquad.com/wp-content/uploads/2026/07/laser-Red-650nm.png" },
  { name: "LCD 16&#215;2 Blue Backlight Display", category: "Display Board & LED", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/LCD-16x2-Blue-Backlight-Display-1-1.png" },
  { name: "LCD 16&#215;2 with I2C Soldered Display", category: "Display Board & LED", price: 280, image: "https://robboquad.com/wp-content/uploads/2026/06/LCD-16x2-with-I2C-Soldered-Display.png" },
  { name: "LCD 20&#215;4 Display | Large Character LCD Module for Arduino & Raspberry Pi", category: "Display Board & LED", price: 499, image: "" },
  { name: "LCD 20&#215;4 Green Backlight Display", category: "Display Board & LED", price: 550, image: "https://robboquad.com/wp-content/uploads/2026/06/LCD-20x4-Green-Backlight-Display.png" },
  { name: "OLED 1.3 Inch White Pixel", category: "Display Board & LED", price: 350, image: "https://robboquad.com/wp-content/uploads/2026/06/1.3-inch-oled-white-display.png" },
  { name: "Original JHD 16&#215;2 Character LCD Display with Green Backlight", category: "Display Board & LED", price: 139, image: "https://robboquad.com/wp-content/uploads/2026/06/lcd-16x2-display.png" },
  { name: "RGB LED- 5mm", category: "Display Board & LED", price: 15, image: "https://robboquad.com/wp-content/uploads/2026/06/RGB-5mm-led.png" },
  { name: "RGB LED- 7mm", category: "Display Board & LED", price: 25, image: "https://robboquad.com/wp-content/uploads/2026/06/135.png" },
  { name: "RTC Timer Relay Module – Real Time Clock 24H Programmable Timer Controller (Copy)", category: "Display Board & LED", price: 3, image: "https://robboquad.com/wp-content/uploads/2026/07/White-Led-5mm.png" },
  { name: "SOIL NPK Sensor RS485", category: "Display Board & LED", price: 2999, image: "https://robboquad.com/wp-content/uploads/2026/06/SOIL-NPK-SENSOR-RS485.png" },
  { name: "TSOP IR Receiver VS1838B", category: "Display Board & LED", price: 20, image: "https://robboquad.com/wp-content/uploads/2026/06/TSOP-IR-Receiver-VS1838B.png" },
  // ESP Boards & Shields
  { name: "ESP-01 WiFi Module ESP8266 Wireless Transceiver", category: "ESP Boards & Shields", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/132.png" },
  { name: "ESP32 C3- Super Mini", category: "ESP Boards & Shields", price: 550, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-C3-Mini.png" },
  { name: "ESP32 CAM WiFi Module Programmer board", category: "ESP Boards & Shields", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-CAM-WiFi-Module-Programmer-board.png" },
  { name: "ESP32 Development Board Type-C USB CH340C WiFi & Bluetooth Dual-Core MCU", category: "ESP Boards & Shields", price: 449, image: "" },
  { name: "ESP32 Expansion Board 30 pins", category: "ESP Boards & Shields", price: 200, image: "https://robboquad.com/wp-content/uploads/2026/07/ESP32-Expansion-Board-30-pins.png" },
  { name: "ESP32 Expansion Board 38 pins", category: "ESP Boards & Shields", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/07/ESP32-Expansion-Board-38-pins.png" },
  { name: "ESP32 S3-FH4R2 Super Mini", category: "ESP Boards & Shields", price: 450, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-S3-FH4R2-Super-Mini.png" },
  { name: "ESP32 WROOM DEVIKIT V1 30 Pins", category: "ESP Boards & Shields", price: 365, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP-32-.png" },
  { name: "ESP32 WROOM Nodemcu 38 Pin", category: "ESP Boards & Shields", price: 600, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-WROOM-Nodemcu-38-Pin.png" },
  { name: "ESP32-CAM WiFi Bluetooth Module with OV2640 2MP Camera Ideal for Face Recognition & IoT Projects", category: "ESP Boards & Shields", price: 699, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP-32-Cam-module-.png" },
  { name: "ESP32-S3-WROOM-1-N16-R8 Development Board", category: "ESP Boards & Shields", price: 520, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-S3-WROOM-1-N16-R8-Development-Board.png" },
  { name: "ESP32-S3-WROOM-1U-N16 official Espressif System-on-Module Chip", category: "ESP Boards & Shields", price: 385, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-S3-WROOM-1U-N16-official-Espressif-System-on-Module-Chip.png" },
  { name: "ESP32-S3-WROOM-1U-N16R8 official Espressif System-on-Module Chip", category: "ESP Boards & Shields", price: 450, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP32-S3-WROOM-1U-N16R8-official-Espressif-System-on-Module-Chip.png" },
  { name: "ESP8266 NodeMCU CP2102 WiFi Module IoT Development Board for Arduino & Smart Projects", category: "ESP Boards & Shields", price: 289, image: "https://robboquad.com/wp-content/uploads/2026/06/128.png" },
  { name: "Mini360 ADJ MP1584 Buck Converter", category: "ESP Boards & Shields", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/07/Mini360-ADJ-MP1584-Buck-Converter.png" },
  { name: "NodeMCU ESP8266 V3 Lua WiFi Development Board (CH340) – Ideal for IoT Projects", category: "ESP Boards & Shields", price: 209, image: "https://robboquad.com/wp-content/uploads/2026/06/ESP-8266-Node-MCU-CH340.png" },
  // Motor Driver & Shield
  { name: "A4988 Stepper Motor Driver", category: "Motor Driver & Shield", price: 139, image: "https://robboquad.com/wp-content/uploads/2026/06/A4988-Stepper-Motor-Driver.png" },
  { name: "Drv8825 Stepper Motor module", category: "Motor Driver & Shield", price: 140, image: "https://robboquad.com/wp-content/uploads/2026/06/Drv-8825-Stepper-Motor-module.png" },
  { name: "L293D Motor Driver Shield for Arduino – Dual H-Bridge Motor Control Board", category: "Motor Driver & Shield", price: 139, image: "https://robboquad.com/wp-content/uploads/2026/06/L293D-Motor-Driver-Shileld-for-Arduino-.png" },
  { name: "L298N Dual H-Bridge Motor Driver Module | DC & Stepper Motor Controller for Arduino & Raspberry Pi", category: "Motor Driver & Shield", price: 140, image: "https://robboquad.com/wp-content/uploads/2026/06/L298N-Dual-H-Bridge.png" },
  { name: "Motor Speed Controller PWM 5A 3-35V", category: "Motor Driver & Shield", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/01_159_1.webp" },
  { name: "MX1508 Mini Motor driver", category: "Motor Driver & Shield", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/07/MX1508-Mini-Motor-driver.png" },
  { name: "N20 gear motor wheels", category: "Motor Driver & Shield", price: 140, image: "https://robboquad.com/wp-content/uploads/2026/06/N20-gear-motor-wheels.png" },
  { name: "PCA9685 16-Channel Servo Motor Driver – I2C PWM Module for Arduino & Raspberry Pi", category: "Motor Driver & Shield", price: 349, image: "https://robboquad.com/wp-content/uploads/2026/06/PCA9685.png" },
  { name: "TB6612FNG Ultra Small Dual DC Motor Driver Module", category: "Motor Driver & Shield", price: 160, image: "https://robboquad.com/wp-content/uploads/2026/07/TB6612FNG-Ultra-Small-Form-match-L298N-perfomance.png" },
  // Motors & Actuators
  { name: "12V Solenoid Valve 1/4&#8243; NPT – 2-Way Normally Closed Brass Electric Valve for Arduino & Raspberry Pi", category: "Motors & Actuators", price: 359, image: "https://robboquad.com/wp-content/uploads/2026/07/Solenoid-valve-12V-for-Arduino_Raspberry-Pi.png" },
  { name: "BO Motor 100 RPM DC Gear Motor for Arduino, Robots & DIY Projects", category: "Motors & Actuators", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/BO-Motors-100-RPM.png" },
  { name: "BO Motor 300 RPM", category: "Motors & Actuators", price: 70, image: "https://robboquad.com/wp-content/uploads/2026/06/BO-Motor-300-rpm.png" },
  { name: "BO Wheels for Robots", category: "Motors & Actuators", price: 35, image: "https://robboquad.com/wp-content/uploads/2026/06/BO-Wheels-for-Robots.png" },
  { name: "Mecanum Wheel Compatible 6.7mm Coupling", category: "Motors & Actuators", price: 50, image: "https://robboquad.com/wp-content/uploads/2026/06/Mecanum-Wheel-Compatible-6.7mm-Coupling.png" },
  { name: "Mecanum Wheels 60mm (4nos)", category: "Motors & Actuators", price: 800, image: "https://robboquad.com/wp-content/uploads/2026/06/Mecanum-Wheels-80mm-4nos.png" },
  { name: "Mecanum Wheels 80mm (4nos)", category: "Motors & Actuators", price: 790, image: "https://robboquad.com/wp-content/uploads/2026/06/Mecanum-Wheels-80mm-4nos.png" },
  { name: "Mini Water Pump 3 to 6V Submersible for DIY Projects", category: "Motors & Actuators", price: 74, image: "https://robboquad.com/wp-content/uploads/2026/06/Mini-Water-Pump-3-6V-Submersible.png" },
  { name: "N20 Gear Motor 300RPM", category: "Motors & Actuators", price: 200, image: "https://robboquad.com/wp-content/uploads/2026/07/N20-Gear-Motor-300rpm.png" },
  { name: "Nvidia Jetson Agx Orin Developer Kit – 32GB", category: "Motors & Actuators", price: 230000, image: "https://robboquad.com/wp-content/uploads/2026/06/Nvidia-Jetson-Agx-Orin-Developer-Kit-32GB.png" },
  { name: "NVIDIA Jetson Orin Super Nano Deployment Kit", category: "Motors & Actuators", price: 56000, image: "https://robboquad.com/wp-content/uploads/2026/06/Nvidia-Jetson-Agx-Orin-Developer-Kit-32GB.png" },
  { name: "TowerPro MG995 Metal Gear Servo Motor 180 Degree Rotation", category: "Motors & Actuators", price: 380, image: "https://robboquad.com/wp-content/uploads/2026/06/TowerPro-MG995-Metal-Gear-Servo-Motor-180-Degree-Rotation.png" },
  { name: "TowerPro SG90 180 Servo Motor Ideal for Arduino, Robots & DIY Projects", category: "Motors & Actuators", price: 139, image: "https://robboquad.com/wp-content/uploads/2026/06/SG-90-Servo-motor.png" },
  { name: "TowerPro SG92R Mini Servo Motor 180 Degree", category: "Motors & Actuators", price: 130, image: "https://robboquad.com/wp-content/uploads/2026/06/TowerPro-SG92R-Mini-Servo-Motor-180-Degree.png" },
  { name: "Toy Motor (5-Pack) 3V-6V DC Hobby Motor for DIY & STEM Projects", category: "Motors & Actuators", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/Toy-Motor-.png" },
  { name: "Vibration Motor", category: "Motors & Actuators", price: 35, image: "https://robboquad.com/wp-content/uploads/2026/06/Vibration-Motor.png" },
  // Power Supply & Converters
  { name: "11.1V 2200mAh 3S LiPo Rechargeable Battery", category: "Power Supply & Converters", price: 1499, image: "https://robboquad.com/wp-content/uploads/2026/07/11.1v_2200mah-Lipo-Battery.png" },
  { name: "12v 1 Amps Adaptor", category: "Power Supply & Converters", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/12v-1-Amps-Adaptor.png" },
  { name: "12V 1A Power Adapter Reliable DC Adaptor for Arduino & DIY Electronics", category: "Power Supply & Converters", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/12v-adaptor.png" },
  { name: "18650 Battery Holder 1 Cell Case", category: "Power Supply & Converters", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/18650-1-Cell-Holder.png" },
  { name: "18650 Battery Holder 2 Cell Case", category: "Power Supply & Converters", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/18640-2-Cell-Holder.png" },
  { name: "18650 Battery Holder 3 Cell Slot with Wire Leads for Lithium-ion Batteries", category: "Power Supply & Converters", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/18640-3-Cell-Holder.png" },
  { name: "18650 Lithium Ion Battery 2200mah 3.7V – Rechargable", category: "Power Supply & Converters", price: 89, image: "https://robboquad.com/wp-content/uploads/2026/06/18650-Lithium-Ion-Battery-2200mah-3.7V-Rechargable.png" },
  { name: "18650 Lithium-Ion Battery 2400mAh 3.7V Rechargeable Battery", category: "Power Supply & Converters", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/127.png" },
  { name: "2S BMS 20A Li-ion", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/08/2S-BMS-20A-Li-ion.png" },
  { name: "3S 10A Lithium Battery BMS Protection Board", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/08/3s-BMS-10A.png" },
  { name: "3S type C BMS", category: "Power Supply & Converters", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/3S-type-C-BMS.png" },
  { name: "5V 1A Power Adapter – Reliable DC Adapter for Electronics & IoT Devices", category: "Power Supply & Converters", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/9v-adaptor.png" },
  { name: "9V 1A Power Adapter Stable DC Adapter for Arduino & Electronics Projects", category: "Power Supply & Converters", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/9v-adaptor.png" },
  { name: "9V HW Battery", category: "Power Supply & Converters", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/9v-Battery-.png" },
  { name: "AA battery holder 4 cell series", category: "Power Supply & Converters", price: 45, image: "https://robboquad.com/wp-content/uploads/2026/06/AA-battery-holder-4-cell-series.png" },
  { name: "CR2032 3V Lithium Coin Cell – CMOS & Timer Battery", category: "Power Supply & Converters", price: 25, image: "https://robboquad.com/wp-content/uploads/2026/08/cr2302-3V-lithium-cell-for-cmos-and-timer.png" },
  { name: "LM2596 Buck Converter Module DC-DC Step Down Power Supply", category: "Power Supply & Converters", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/LM2596-Buck-Converter-Standard-Quality.png" },
  { name: "Mini 560 Pro 5V Buck converter", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/06/Mini-560-Pro-5V-Buck-converter.png" },
  { name: "Mini560 12V 5A DC-DC Buck Converter", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/07/Mini-560-12V-Buck-converter.png" },
  { name: "MT3608 Boost Converter", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/06/MT3608-boost-convertor.png" },
  { name: "MT3608 Boost Convertor Step up Module with micro B pin", category: "Power Supply & Converters", price: 65, image: "https://robboquad.com/wp-content/uploads/2026/07/MT3608-Boost-Convertor-Step-up-Module-with-micro-B-pin.png" },
  { name: "P-DEAN Connector (Male & Female Pair)", category: "Power Supply & Converters", price: 35, image: "https://robboquad.com/wp-content/uploads/2026/07/P-DEAN-Connector.png" },
  { name: "Solar Panel Small 3.3V", category: "Power Supply & Converters", price: 65, image: "https://robboquad.com/wp-content/uploads/2026/06/Solar-Panel-Small-3.3V.png" },
  { name: "TP4056 Micro USB Lithium Battery Charging Module with Protection", category: "Power Supply & Converters", price: 35, image: "https://robboquad.com/wp-content/uploads/2026/07/TP4056-Micro-B.png" },
  { name: "tp4056 type – C 18650 1 Cell Lithium Ion Charger", category: "Power Supply & Converters", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/tp4056.jpg" },
  { name: "Tp4056 type C 1 cell Lithium Ion Battery BMS", category: "Power Supply & Converters", price: 45, image: "https://robboquad.com/wp-content/uploads/2026/06/Tp4056-type-c.png" },
  { name: "XL4015 Buck Converter 3A–5A and MT3608 boost convertor@6019", category: "Power Supply & Converters", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/XL4015-Buck-Converter-3A–5A.png" },
  { name: "XL6009 DC-DC Step Up Boost Converter Module", category: "Power Supply & Converters", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/06/XL6009-DC-DC-Step-Up-Boost-Converter-Module.png" },
  { name: "XT60 Connector Set (Male & Female)", category: "Power Supply & Converters", price: 45, image: "https://robboquad.com/wp-content/uploads/2026/07/XT60-CONNECTOR-Set.png" },
  // Quadcopter & Drones
  { name: "10&#215;4.5 Quadcopter Propeller Set Durable Drone Blades for DIY Multi rotors", category: "Quadcopter & Drones", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/104.5-Propeller-.png" },
  { name: "1000KV BLDC Brushless Motor High Torque Motor for Drones & RC Projects", category: "Quadcopter & Drones", price: 459, image: "https://robboquad.com/wp-content/uploads/2026/06/1000kv-BLDC-Motor-.png" },
  { name: "30A Simonk ESC Brushless Motor Speed Controller for Quadcopters & DIY Drones", category: "Quadcopter & Drones", price: 369, image: "https://robboquad.com/wp-content/uploads/2026/06/30A-Simonk-ESC.png" },
  { name: "920KV 2212 BLDC Motor", category: "Quadcopter & Drones", price: 890, image: "https://robboquad.com/wp-content/uploads/2026/06/920KV-2212-BLDC-Motor-1.png" },
  { name: "APM 2.8 Flight Controller", category: "Quadcopter & Drones", price: 4999, image: "https://robboquad.com/wp-content/uploads/2026/06/APM-2.8-Flight-Controller.png" },
  { name: "B3 IMAX LiPo/Li-ion Battery Charger 2S/3S Balance Charger for RC, Drones & DIY Projects", category: "Quadcopter & Drones", price: 339, image: "https://robboquad.com/wp-content/uploads/2026/06/B3-Ima.png" },
  { name: "F550 Drone Frame with landing gears", category: "Quadcopter & Drones", price: 3000, image: "https://robboquad.com/wp-content/uploads/2026/06/F550-Drone-Frame-with-landing-gears.png" },
  { name: "gps pixhawk", category: "Quadcopter & Drones", price: 1599, image: "https://robboquad.com/wp-content/uploads/2026/06/gps-pixhawk.png" },
  { name: "Pixhawk 2.4.8 Flight Controller", category: "Quadcopter & Drones", price: 5999, image: "https://robboquad.com/wp-content/uploads/2026/06/Pixhawk-2.4.8-Flight-Controller.png" },
  { name: "Pixhawk 6c", category: "Quadcopter & Drones", price: 35999, image: "https://robboquad.com/wp-content/uploads/2026/06/Pixhawk-6c.png" },
  { name: "XYQ-2 Wooden DIY Drone Kit", category: "Quadcopter & Drones", price: 2799, image: "https://robboquad.com/wp-content/uploads/2026/06/xy-q2-wooden-diy-drone-kit.jpg" },
  // Relays
  { name: "1 Channel 5V Relay Module for Arduino, Raspberry Pi & Microcontrollers", category: "Relays", price: 59, image: "https://robboquad.com/wp-content/uploads/2026/06/Relay-1-Channel-5V.png" },
  { name: "2 Channel 5V Relay Module for Arduino, Raspberry Pi & Microcontrollers", category: "Relays", price: 89, image: "https://robboquad.com/wp-content/uploads/2026/06/Relay-2-Channel-5V.png" },
  { name: "4 Channel 5V Relay Module for Arduino, Raspberry Pi & Microcontrollers", category: "Relays", price: 169, image: "https://robboquad.com/wp-content/uploads/2026/06/Relay-4-Chennel-5V.png" },
  { name: "Relay 1 Channel 12v", category: "Relays", price: 110, image: "https://robboquad.com/wp-content/uploads/2026/06/Relay-1-Channel-12v.png" },
  { name: "Relay 2 Channel 12v", category: "Relays", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/Relay-2-Channel-12v.png" },
  { name: "RTC Timer Relay Module – Real Time Clock 24H Programmable Timer Controller", category: "Relays", price: 890, image: "https://robboquad.com/wp-content/uploads/2026/07/RTC-timer-Relay-module.png" },
  { name: "Timer Relay Module", category: "Relays", price: 449, image: "https://robboquad.com/wp-content/uploads/2026/07/Timer-relay-module.png" },
  // Resistor & Capacitors
  { name: "0.1uf 50v Disc Capacitor", category: "Resistor & Capacitors", price: 1, image: "https://robboquad.com/wp-content/uploads/2026/06/0.1uf-50v-Disc-Capacitor-1.png" },
  { name: "100 Ohm 0.25W Metal Film Resistor", category: "Resistor & Capacitors", price: 1.5, image: "https://robboquad.com/wp-content/uploads/2026/06/10k-Ohm-0.25W-Metal-Film-Resistor.png" },
  { name: "100k ohm 0.25W ± 5 Axial leaded", category: "Resistor & Capacitors", price: 1.5, image: "https://robboquad.com/wp-content/uploads/2026/06/100k-ohm-0.25W-±-5-Axial-leaded.png" },
  { name: "100k Potentiometer – Pack of 5 Pieces", category: "Resistor & Capacitors", price: 9, image: "https://robboquad.com/wp-content/uploads/2026/06/126.png" },
  { name: "10k Ohm 0.5W Metal Film Resistor", category: "Resistor & Capacitors", price: 1.5, image: "https://robboquad.com/wp-content/uploads/2026/06/10k-Ohm-0.25W-Metal-Film-Resistor.png" },
  { name: "10k Potentiometer – Pack of 5 Pieces", category: "Resistor & Capacitors", price: 9, image: "https://robboquad.com/wp-content/uploads/2026/06/125.png" },
  { name: "10uF 50V 1.82Ω@100kHz ±20% 120mA@100kHz Plugin,D5xL11mm Aluminum Electrolytic Capacitors", category: "Resistor & Capacitors", price: 9, image: "https://robboquad.com/wp-content/uploads/2026/06/10uF-50V-1.82Ω@100kHz-±20-120mA@100kHz-PluginD5xL11mm-Aluminum-Electrolytic-Capacitors.png" },
  { name: "1k Ohm 0.25W Metal Film Resistor", category: "Resistor & Capacitors", price: 2, image: "https://robboquad.com/wp-content/uploads/2026/06/1k-Ohm-0.25W-Metal-Film-Resistor.png" },
  { name: "220 ohms resistor", category: "Resistor & Capacitors", price: 1.5, image: "https://robboquad.com/wp-content/uploads/2026/06/220-ohms-resistor.png" },
  { name: "330 Ohm 0.25W Metal Film Resistor", category: "Resistor & Capacitors", price: 1, image: "https://robboquad.com/wp-content/uploads/2026/06/330-Ohm-0.25W-Metal-Film-Resistor.png" },
  // Robotic Kits
  { name: "2WD Robot Chassis Kit for Arduino & Raspberry Pi Smart Car", category: "Robotic Kits", price: 260, image: "https://robboquad.com/wp-content/uploads/2026/06/2WD-Robot-Chassis-Kit.png" },
  { name: "4 Wheel suspension Kit – Advanced", category: "Robotic Kits", price: 1300, image: "https://robboquad.com/wp-content/uploads/2026/06/4-Wheel-suspension-Kit-Advanced.png" },
  { name: "4WD Robot Chassis Kit for Arduino & Raspberry Pi Smart Rover", category: "Robotic Kits", price: 500, image: "https://robboquad.com/wp-content/uploads/2026/06/4WD-Robot-Chassis-Kit.png" },
  { name: "6 Wheel suspension Kit – Advanced", category: "Robotic Kits", price: 2000, image: "https://robboquad.com/wp-content/uploads/2026/06/6-Wheel-suspension-Kit-Advanced.png" },
  // Sensors & Modules
  { name: "10 KG Load Cell", category: "Sensors & Modules", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/10-kg-load-cell.jpg" },
  { name: "12V Electric Solenoid Lock for Arduino, Raspberry Pi & Smart Access Control Projects", category: "Sensors & Modules", price: 399, image: "https://robboquad.com/wp-content/uploads/2026/06/solenoid-lock.png" },
  { name: "2.4GHz NRF24L01+PA+LNA SMA Wireless Transceiver Antenna", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/2.4GHz-NRF24L01PALNA-SMA-Wireless-Transceiver-Antenna.png" },
  { name: "27mm Piezoelectric Disc – Piezo Ceramic Transducer & Sound Sensor", category: "Sensors & Modules", price: 30, image: "https://robboquad.com/wp-content/uploads/2026/08/27mm-Piezoelectric-disc.png" },
  { name: "37 IN ONE SENSOR KIT FOR ARDUINO RASPBERRY PI ESP32", category: "Sensors & Modules", price: 1200, image: "https://robboquad.com/wp-content/uploads/2026/06/37-IN-ONE-SENSOR-KIT-FOR-ARDUINO-_-RASPBERRY-PI-_-ESP32-1.png" },
  { name: "3mm LDR Sensor Light Dependent Resistor", category: "Sensors & Modules", price: 10, image: "https://robboquad.com/wp-content/uploads/2026/06/104.png" },
  { name: "4 Channel 27MHZ Toy Module", category: "Sensors & Modules", price: 160, image: "https://robboquad.com/wp-content/uploads/2026/06/4-Channel-27MHZ-Toy-Module.png" },
  { name: "4&#215;4 Matrix Keypad Module for Arduino & Raspberry Pi | 16-Button Input Keyboard", category: "Sensors & Modules", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/Keypad-Module.png" },
  { name: "5 KG Load Cell", category: "Sensors & Modules", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/5-kg-load.jpg" },
  { name: "5V Powerbank Charging Module | Li-ion Battery Boost Converter for DIY Projects", category: "Sensors & Modules", price: 69, image: "https://robboquad.com/wp-content/uploads/2026/06/Powerbank-Module-.png" },
  { name: "8 ohms speaker", category: "Sensors & Modules", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/8-ohms-speaker.png" },
  { name: "AD620 Instrumentation Amplifier Module – Precision Microvolt/Millivolt Amplifier", category: "Sensors & Modules", price: 359, image: "https://robboquad.com/wp-content/uploads/2026/08/AD620-Instrumentation-Amplifier.png" },
  { name: "ADS1115 16-Bit 4-Channel ADC Module with Programmable Gain Amplifier (PGA)", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/08/ADS1115-16Bit-PGA-ADC-4-channel.png" },
  { name: "ADXL345 Triple Axis Digital Accelerometer Module", category: "Sensors & Modules", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/ADXL345.png" },
  { name: "Analog Joystick Module", category: "Sensors & Modules", price: 100, image: "https://robboquad.com/wp-content/uploads/2026/06/Analog-Joystick-Module.png" },
  { name: "BH1750 Ambient Light Sensor Module Digital Lux Meter with I²C Interface", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/08/BH1750-Ambient-Light-Sensor.png" },
  { name: "BME280 Temperature, Humidity, and Pressure Sensor Module", category: "Sensors & Modules", price: 450, image: "https://robboquad.com/wp-content/uploads/2026/08/BME280-Temperature_Humidity-Pressure-Sensor.png" },
  { name: "BMP180 Digital Barometric Pressure Sensor Module", category: "Sensors & Modules", price: 49, image: "https://robboquad.com/wp-content/uploads/2026/06/bmp-180-pressure-sensor-.png" },
  { name: "BMP280 Temperature and Pressure Sensor – Digital Barometric Sensor Module", category: "Sensors & Modules", price: 100, image: "https://robboquad.com/wp-content/uploads/2026/08/BMP280-Temperature-and-Pressure-Sensor.png" },
  { name: "Breadboard power supply", category: "Sensors & Modules", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/TDS-Sensor-Module-2.png" },
  { name: "Buzzer Small – 5V Piezo Beeper", category: "Sensors & Modules", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/buzzer.png" },
  { name: "Can Module MCp2515", category: "Sensors & Modules", price: 1140, image: "https://robboquad.com/wp-content/uploads/2026/06/Can-Module-MCp2515.png" },
  { name: "capacitive soil moisture V2.0", category: "Sensors & Modules", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/06/capacitive-soil-moisture-V2.0.png" },
  { name: "CH340G to TTL Serial Converter", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/CH340G-to-TTL-Serial-Converter.png" },
  { name: "Current Sensor Module for Arduino & Raspberry Pi | ACS712", category: "Sensors & Modules", price: 119, image: "https://robboquad.com/wp-content/uploads/2026/06/Current-Sensor.png" },
  { name: "DF Mini Player Mp3 Module", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/DF-Mini-Player-Mp3-Module.png" },
  { name: "DHT 22 Temperature and Humidity Sensor", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/DHT-22-Temperature-and-Humidity-Sensor.png" },
  { name: "DHT11 Temperature and Humidity Sensor Module", category: "Sensors & Modules", price: 74, image: "https://robboquad.com/wp-content/uploads/2026/06/DHT-11.png" },
  { name: "DIY Mini Tesla Coil Kit (Wireless Electric Power Transmission)", category: "Sensors & Modules", price: 500, image: "https://robboquad.com/wp-content/uploads/2026/06/DIY-Tesla-Coil-Mini-Kit-Wireless-Electric-Power-Transmission.png" },
  { name: "DS18B20 Water Proof Digital Temperature Probe – Black (1m)", category: "Sensors & Modules", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/DS18B20-Water-Proof-Digital-Temperature-Probe-–-Black-1m.png" },
  { name: "DS3231 RTC Timer Module for Arduino & Raspberry Pi | High-Precision Real Time Clock", category: "Sensors & Modules", price: 169, image: "https://robboquad.com/wp-content/uploads/2026/06/DS3231-RTC-timer-module-.png" },
  { name: "EMG Sensor Kit", category: "Sensors & Modules", price: 1140, image: "https://robboquad.com/wp-content/uploads/2026/06/EMG-Sensor-Kit.png" },
  { name: "Eye Blink Sensor", category: "Sensors & Modules", price: 269, image: "https://robboquad.com/wp-content/uploads/2026/06/Eye-Blink-Sensor.png" },
  { name: "Flame Sensor Module for Fire Detection & Safety Systems", category: "Sensors & Modules", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/Flame-Sensor-Module-.png" },
  { name: "Flex Sensor 2.2Inches", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/Flex-Sensor-2.2Inches-2.png" },
  { name: "Flex Sensor 4.5Inches", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/Flex-Sensor-2.2Inches.png" },
  { name: "Float Sensor", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/Float-Sensor.png" },
  { name: "Force Sensor Circle Shape", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/Force-Sensor-Circle-Shape.png" },
  { name: "Force Sensor Square Shape", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/Force-Sensor-Square-Shape.png" },
  { name: "FT232RL to UART TTL Converter", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/FT232RL-to-UART-TTL-Converter.png" },
  { name: "GP2Y1010AU0F Optical Dust Sensor", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/Dust-Sensor-GP2Y1010AU0F.png" },
  { name: "GPS NEO 6M with Patch Antenna", category: "Sensors & Modules", price: 269, image: "https://robboquad.com/wp-content/uploads/2026/06/GPS-NEO-6M-with-Patch-Antenna-1.png" },
  { name: "GSM Sim 800L Module", category: "Sensors & Modules", price: 698, image: "https://robboquad.com/wp-content/uploads/2026/06/GSM-Sim-800L-Module.png" },
  { name: "Hall effect sensor module", category: "Sensors & Modules", price: 100, image: "https://robboquad.com/wp-content/uploads/2026/06/Hall-effect-sensor-module.png" },
  { name: "HC-05 Bluetooth Module for Wireless Communication Projects", category: "Sensors & Modules", price: 299, image: "https://robboquad.com/wp-content/uploads/2026/06/Hc05-bluetooth-module.png" },
  { name: "HC-12 Wireless Serial Module – 433MHz Long Range Transceiver", category: "Sensors & Modules", price: 450, image: "https://robboquad.com/wp-content/uploads/2026/08/HC12-Module.png" },
  { name: "HC-SR04 Ultrasonic sensor for Arduino/Raspberry Pi", category: "Sensors & Modules", price: 74, image: "https://robboquad.com/wp-content/uploads/2026/06/hc-sr04-ultrasonic-sensor-1.png" },
  { name: "Hx710B Air Pressure Sensor", category: "Sensors & Modules", price: 490, image: "https://robboquad.com/wp-content/uploads/2026/06/Hx710B-Air-Pressure.png" },
  { name: "HX711 Dual-Channel 24 Bit Precision A/D weight Pressure Sensor", category: "Sensors & Modules", price: 129, image: "https://robboquad.com/wp-content/uploads/2026/06/hx711.jpg" },
  { name: "INMP441 MEMS High Precision Omnidirectional Microphone I2S", category: "Sensors & Modules", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/07/INMP441-MEMS-High-Precision-Omnidirectional-Microphone-I2S.png" },
  { name: "IR Infrared Obstacle Avoidance Sensor Module for Robotics & Automation", category: "Sensors & Modules", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/IR-Sensor-Module-1.png" },
  { name: "IR Led Pair", category: "Sensors & Modules", price: 15, image: "https://robboquad.com/wp-content/uploads/2026/06/IR-Led-Pair.png" },
  { name: "IR Remote Control Module for Arduino, Raspberry Pi & Microcontrollers | Infrared Receiver", category: "Sensors & Modules", price: 189, image: "https://robboquad.com/wp-content/uploads/2026/06/IR-remote-module-.png" },
  { name: "Laser Diode Module 5mw 650nm 5V", category: "Sensors & Modules", price: 100, image: "https://robboquad.com/wp-content/uploads/2026/06/Laser-Diode-Module-5mw-650nm-5V.png" },
  { name: "LDR Light Sensor Module for Arduino, Raspberry Pi & Smart Lighting Projects", category: "Sensors & Modules", price: 49, image: "https://robboquad.com/wp-content/uploads/2026/06/LDR-Sensor-Module-.png" },
  { name: "LM 35 Temperature Sensor", category: "Sensors & Modules", price: 89, image: "https://robboquad.com/wp-content/uploads/2026/06/LM35.jpg" },
  { name: "Magnet Door Sensor Reed Switch", category: "Sensors & Modules", price: 90, image: "https://robboquad.com/wp-content/uploads/2026/06/magnet-Door-Sensor.png" },
  { name: "MAX1279 8 x 8 Matrix Led", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/MAX1728-8-x-8-Matrix-Led.png" },
  { name: "MAX30100 Pulse Oximeter Heart Rate Sensor Module", category: "Sensors & Modules", price: 149, image: "https://robboquad.com/wp-content/uploads/2026/06/MAX30100.jpg" },
  { name: "MAX30102 Pulse Oximeter Heart Rate Sensor Module", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/MAX30102-Pulse-Oximeter-Heart-Rate-Sensor-Module.png" },
  { name: "MAX31865 RTD Platinum Resistance Temperature Detector (RTD) to Digital Converter Module", category: "Sensors & Modules", price: 590, image: "https://robboquad.com/wp-content/uploads/2026/08/MAX31865-RTD-Platinum-Resistance-Temperature-Detector-to-Digital-Converter.png" },
  { name: "MAX9837A audio Amplifier", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/07/MAX9837A-audio-Amplifier.png" },
  { name: "Microphone Sound Sensor Module for Arduino & Raspberry Pi | Audio Detection Module", category: "Sensors & Modules", price: 129, image: "https://robboquad.com/wp-content/uploads/2026/06/Microphone-module.png" },
  { name: "MLX90614 temprature sensor", category: "Sensors & Modules", price: 650, image: "https://robboquad.com/wp-content/uploads/2026/06/MLX90614-temperature-sensor.png" },
  { name: "MPR121 Capacitive Touch Sensor Module", category: "Sensors & Modules", price: 140, image: "https://robboquad.com/wp-content/uploads/2026/08/MPR121-Capacitive-Touch-Sensor-Module.png" },
  { name: "MPU 6050 6 axis Accelerometer & Gyroscope", category: "Sensors & Modules", price: 199, image: "https://robboquad.com/wp-content/uploads/2026/06/MPU-6050-6-axis-Accelerometer-Gyroscope-2.png" },
  { name: "MPU 9250 6-Axis Attitude Gyro and Accelero Sensor Module", category: "Sensors & Modules", price: 899, image: "https://robboquad.com/wp-content/uploads/2026/06/mpu-9250.png" },
  { name: "MQ 7 Gas Sensor for Arduino/Raspberry Pi", category: "Sensors & Modules", price: 109, image: "https://robboquad.com/wp-content/uploads/2026/06/MQ-7-Gas-Sensor-1.png" },
  { name: "MQ135 Gas Sensor for Arduino/Raspberry Pi", category: "Sensors & Modules", price: 109, image: "https://robboquad.com/wp-content/uploads/2026/06/MQ135-Gas-Sensor-1.png" },
  { name: "MQ2 Gas Sensor for Arduino/Raspberry Pi", category: "Sensors & Modules", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/MQ2-Gas-Sensor-2.png" },
  { name: "NRF24L01 module adapter board", category: "Sensors & Modules", price: 50, image: "https://robboquad.com/wp-content/uploads/2026/06/NRF24L01-module-adapter-board.png" },
  { name: "Peacefair PZEM-004T AC Multi-function Energy Meter Module", category: "Sensors & Modules", price: 995, image: "https://robboquad.com/wp-content/uploads/2026/08/Peacefair-PZEM-004T-AC-Voltage-Current-Power-Energy-Frequency-Power-Factor-Meter-Module.png" },
  { name: "PIR Motion Detector Sensor Module for Arduino, Raspberry Pi & IoT Projects", category: "Sensors & Modules", price: 79, image: "https://robboquad.com/wp-content/uploads/2026/06/PIR-Motion-detectorSensor.png" },
  { name: "Pulse Rate & Heartbeat Sensor Module for Arduino & Raspberry Pi | Optical Detection", category: "Sensors & Modules", price: 174, image: "https://robboquad.com/wp-content/uploads/2026/06/Heart-Sensor-.png" },
  { name: "R305 Fingerprint Sensor Module for Arduino & Raspberry Pi | Biometric Access Control", category: "Sensors & Modules", price: 1399, image: "https://robboquad.com/wp-content/uploads/2026/06/Fingerprint-Sensor-.png" },
  { name: "Rain Drop Sensor", category: "Sensors & Modules", price: 75, image: "https://robboquad.com/wp-content/uploads/2026/06/Rain-Drop-Sensor.png" },
  { name: "RC522 RFID Module for Arduino & Raspberry PI", category: "Sensors & Modules", price: 99, image: "https://robboquad.com/wp-content/uploads/2026/06/RC522-RFID-Module-1.png" },
  { name: "Reed Sensor Magnetic Switch Module", category: "Sensors & Modules", price: 60, image: "https://robboquad.com/wp-content/uploads/2026/07/Reed-Sensor.png" },
  { name: "RF 433MHz Wireless Transmitter and Receiver Module for Arduino & IoT Projects", category: "Sensors & Modules", price: 169, image: "https://robboquad.com/wp-content/uploads/2026/06/RF-TXRX-433-MHZ.png" },
  { name: "RF Module TX/RX 433 MHZ (Green)", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/06/RF-Module-TX_RX-433-MHZ-Green.png" },
  { name: "RS232 to TTL module", category: "Sensors & Modules", price: 80, image: "https://robboquad.com/wp-content/uploads/2026/06/RS232-to-ttl-module.png" },
  { name: "RS485 to TTL module", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/RS485-to-ttl-module.png" },
  { name: "RS485 TTL Auto Direction", category: "Sensors & Modules", price: 70, image: "https://robboquad.com/wp-content/uploads/2026/06/RS485-TTL-Auto-Direction.png" },
  { name: "RS485 Usb Adapter", category: "Sensors & Modules", price: 120, image: "https://robboquad.com/wp-content/uploads/2026/06/RS485-USB-ADAPTER.png" },
  { name: "SD Card Module", category: "Sensors & Modules", price: 76, image: "https://robboquad.com/wp-content/uploads/2026/06/SD-Card-Module.png" },
  { name: "Seeed Studio XIAO BLE nRF52840", category: "Sensors & Modules", price: 2250, image: "https://robboquad.com/wp-content/uploads/2026/06/Seeed-Studio-XIAO-BLE-nRF52840.png" },
  { name: "SIM900A GSM GPRS Module for Arduino & Raspberry Pi | Wireless Communication Module", category: "Sensors & Modules", price: 1099, image: "https://robboquad.com/wp-content/uploads/2026/06/GSM-Module-SIM900A.png" },
  { name: "SN65HVD230 / MCP2551 CAN Bus Transceiver Module", category: "Sensors & Modules", price: 150, image: "https://robboquad.com/wp-content/uploads/2026/07/SN65H-MCP2551-CAN-Transreciever.png" },
  { name: "Soil Moisture Sensor Module for Arduino, Raspberry Pi & Smart Farming Projects", category: "Sensors & Modules", price: 59, image: "https://robboquad.com/wp-content/uploads/2026/06/Soil-Moisture-Sensor-1.png" },
  { name: "Soil pH Sensor with Probe – Industrial Grade Soil Acidity Transducer", category: "Sensors & Modules", price: 1950, image: "https://robboquad.com/wp-content/uploads/2026/08/Soil-PH-Sensor-with-Probe.png" },
  { name: "Stepper Motor(28YBJ-48)", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/Stepper-Motor28YBJ-48.png" },
  { name: "Stepper Motor(28YBJ-48) ULN2003 Driver Board", category: "Sensors & Modules", price: 100, image: "https://robboquad.com/wp-content/uploads/2026/06/Stepper-Motor28YBJ-48-2.png" },
  { name: "Stepper Motor(28YBJ-48) with ULN2003 Driver Board", category: "Sensors & Modules", price: 280, image: "https://robboquad.com/wp-content/uploads/2026/06/uln2003-stepper.jpg" },
  { name: "SW-420 Vibration Sensor Module", category: "Sensors & Modules", price: 59, image: "https://robboquad.com/wp-content/uploads/2026/06/122.png" },
  { name: "SX1278 LoRa Module Ra- 02 433MHZ Wireless Spread Spectrum Transmission", category: "Sensors & Modules", price: 500, image: "https://robboquad.com/wp-content/uploads/2026/06/SX1278-LoRa-Module-Ra-02-433MHZ-Wireless-Spread-Spectrum-Transmission.png" },
  { name: "TCS3200 Color Sensor Module for Arduino | RGB Color Detection for MCU Projects", category: "Sensors & Modules", price: 419, image: "https://robboquad.com/wp-content/uploads/2026/06/Colour-Sensor-.png" },
  { name: "TDS Sensor Module", category: "Sensors & Modules", price: 1140, image: "https://robboquad.com/wp-content/uploads/2026/06/TDS-Sensor-Module.png" },
  { name: "TEC1-12710 PELTIER Thermoelectric Module", category: "Sensors & Modules", price: 500, image: "https://robboquad.com/wp-content/uploads/2026/06/tec1-12710-PELTIER-1.png" },
  { name: "Tilt Sensor Module", category: "Sensors & Modules", price: 1140, image: "https://robboquad.com/wp-content/uploads/2026/06/Tilt-sensor.png" },
  { name: "Touch Sensor", category: "Sensors & Modules", price: 50, image: "https://robboquad.com/wp-content/uploads/2026/06/Touch-Sensor.png" },
  { name: "Traffic Light Module – 3-Color LED Signal Light for Arduino", category: "Sensors & Modules", price: 50, image: "https://robboquad.com/wp-content/uploads/2026/08/Traffic-Light-Module.png" },
  { name: "Turbidity Sensor", category: "Sensors & Modules", price: 655, image: "https://robboquad.com/wp-content/uploads/2026/06/Turbidity-Sensor.png" },
  { name: "Ultrasonic Holder", category: "Sensors & Modules", price: 25, image: "https://robboquad.com/wp-content/uploads/2026/06/Ultrasonic-Holder.png" },
  { name: "Ultrasonic Mist Maker Humidifier", category: "Sensors & Modules", price: 250, image: "https://robboquad.com/wp-content/uploads/2026/06/ultrasonic-mist-maker.png" },
  { name: "VL53L0X Time-of-Flight (ToF) Laser Distance Sensor Module", category: "Sensors & Modules", price: 160, image: "https://robboquad.com/wp-content/uploads/2026/07/VL53L0X-TOF-Laser-Distance-Sensor.png" },
  { name: "Voltage Sensor Module for Arduino & Raspberry Pi | 0-25V DC Voltage Detection", category: "Sensors & Modules", price: 39, image: "https://robboquad.com/wp-content/uploads/2026/06/Voltage-Sensor-.png" },
  { name: "Water flow Sensor – YFS201", category: "Sensors & Modules", price: 180, image: "https://robboquad.com/wp-content/uploads/2026/06/Water-flow-Sensor-YFS201.png" },
  { name: "Water flow Sensor – YFS401", category: "Sensors & Modules", price: 350, image: "https://robboquad.com/wp-content/uploads/2026/06/Water-flow-Sensor-YFS401.png" },
  { name: "Water Level Sensor", category: "Sensors & Modules", price: 70, image: "https://robboquad.com/wp-content/uploads/2026/06/Water-Level-Sensor.png" },
  { name: "Waterproof Ultrasonic Sensor with Probe", category: "Sensors & Modules", price: 90, image: "https://robboquad.com/wp-content/uploads/2026/06/Water-proof-ultrasonic-sensor-with-probe.png" },
  { name: "ZMCT103C AC Current Sensor Module", category: "Sensors & Modules", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/ZMCT103C-AC-Current-Sensor.png" },
  { name: "ZMPT101B AC voltage sensor Module", category: "Sensors & Modules", price: 500, image: "https://robboquad.com/wp-content/uploads/2026/06/ZMPT101B-AC-voltage-sensor.png" },
  // STM32
  { name: "ST Link V2 Programmer", category: "STM32", price: 225, image: "https://robboquad.com/wp-content/uploads/2026/06/ST-Link-V2.png" },
  { name: "STM32F103C8T6 blue pill", category: "STM32", price: 234, image: "https://robboquad.com/wp-content/uploads/2026/06/STM32F103C8T6-blue-pill.png" },
  // Transistors & IC
  { name: "16-Pin IC Base (DIP Socket)", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/IC-base-16-pin.png" },
  { name: "7805 5V 500mA Regulator IC", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/7805-IC.png" },
  { name: "BC547 Transistor – (Pack of 5 Pieces)", category: "Transistors & IC", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/98.png" },
  { name: "CD4017 Decade Counter IC", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/CD4017-IC.png" },
  { name: "Combo – 1N 4007 Diode – Pack of 5 Pieces", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/97.png" },
  { name: "Combo – 555 Timer IC (5 Pieces)", category: "Transistors & IC", price: 44, image: "https://robboquad.com/wp-content/uploads/2026/06/99.png" },
  { name: "IC 7404 Hex Inverter (NOT Gate)", category: "Transistors & IC", price: 30, image: "https://robboquad.com/wp-content/uploads/2026/06/7404-IC.png" },
  { name: "IC 7408 Quad 2-Input AND Gate", category: "Transistors & IC", price: 44, image: "" },
  { name: "IC 7432 Quad 2-Input OR Gate", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/7432-IC.png" },
  { name: "IC 7474 Dual D-Type Flip-Flop", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/IC7474.png" },
  { name: "IRF540N 2-3V Vgs N – Channel Mosfet", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/IRF540N_IRL74NN.png" },
  { name: "LM741 Comparator / Operational Amplifier", category: "Transistors & IC", price: 44, image: "https://robboquad.com/wp-content/uploads/2026/06/LM741-Comparator.png" },
  { name: "PC817 Optocoupler (Opto-Isolator IC)", category: "Transistors & IC", price: 29, image: "https://robboquad.com/wp-content/uploads/2026/06/PC817-Opto-coupler.png" },
  { name: "TIP122 NPN Power Transistor", category: "Transistors & IC", price: 14, image: "https://robboquad.com/wp-content/uploads/2026/06/TIP122-NPN-Power-Transistor.png" },
]

export const products: Product[] = raw.map((p, i) => ({
  id: String(i + 1),
  name: p.name,
  category: p.category,
  price: applyMargin(p.price),
  baseCost: p.price,
  image: p.image,
  inStock: p.inStock !== false,
}))

export const categories: string[] = Array.from(new Set(products.map((p) => p.category))).sort()
